import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { memorialAbsoluteUrl, memorialPagePath } from '@/lib/memorial-share'
import { getMemorialWithDetails } from '@/lib/memorial-store'
import { getSiteOrigin } from '@/lib/site-url'
import { MemorialPrintToolbar } from '../print/print-toolbar'

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>
}): Promise<Metadata> {
  const { slug } = await params
  const data = await getMemorialWithDetails(slug)
  if (!data) return { title: 'Printer guide · Passage' }
  const origin = getSiteOrigin()
  return {
    title: `${data.deceased_name} — printer guide · Passage`,
    description: `What to give your print shop for ${data.deceased_name}.`,
    alternates: { canonical: `${origin}${memorialPagePath(slug)}/printer-guide` },
    robots: { index: false, follow: true },
  }
}

export default async function MemorialPrinterGuidePage({
  params,
}: {
  params: Promise<{ slug: string }>
}) {
  const { slug } = await params
  const data = await getMemorialWithDetails(slug)
  if (!data) notFound()

  const memorialUrl = memorialAbsoluteUrl(slug)

  return (
    <div className="memorial-print-root mx-auto max-w-2xl px-4 py-8 font-sans text-[#1A1A1A]">
      <MemorialPrintToolbar />

      <header className="mb-8">
        <p className="text-xs font-semibold uppercase tracking-widest text-[#C9A02C]">Hand to printer</p>
        <h1 className="mt-2 text-2xl font-semibold">{data.deceased_name}</h1>
        <p className="mt-2 text-sm text-[#1A1A1A]/75">
          One-page brief for your print shop — sizes, file types, and Passage links.
        </p>
      </header>

      <section className="mb-6 space-y-3 text-sm leading-relaxed">
        <h2 className="font-semibold text-[#3D2B1F]">Programme sheet (A4)</h2>
        <ul className="list-disc space-y-1 pl-5 text-[#1A1A1A]/85">
          <li>Trim: A4 portrait (210 × 297mm).</li>
          <li>Export: open the programme print page → browser Print → Save as PDF.</li>
          <li>Photos: supply high-resolution originals if the shop requests them.</li>
          <li>Colour: ask whether CMYK conversion from your PDF is required.</li>
        </ul>
        <p>
          <Link href={`/memorial/${slug}/print`} className="font-medium text-[#C9A02C] underline">
            Open programme print sheet →
          </Link>
        </p>
      </section>

      <section className="mb-6 space-y-3 text-sm leading-relaxed">
        <h2 className="font-semibold text-[#3D2B1F]">Roll-up banner (850 × 2000mm)</h2>
        <ul className="list-disc space-y-1 pl-5 text-[#1A1A1A]/85">
          <li>Standard outdoor roll-up: 850mm wide × 2000mm tall (include bleed per shop spec).</li>
          <li>Includes hero photo, announcement excerpt, and QR code to the memorial page.</li>
          <li>Test the QR after printing: {memorialUrl}</li>
        </ul>
        <p>
          <Link href={`/memorial/${slug}/banner`} className="font-medium text-[#C9A02C] underline">
            Open roll-up banner layout →
          </Link>
        </p>
      </section>

      <section className="mb-6 space-y-3 text-sm leading-relaxed">
        <h2 className="font-semibold text-[#3D2B1F]">Wide banner (3 × 6 ft style)</h2>
        <ul className="list-disc space-y-1 pl-5 text-[#1A1A1A]/85">
          <li>Logical aspect ~1:2 (915 × 1830mm / 3ft × 6ft) — landscape-oriented vinyl or mesh.</li>
          <li>Same content as roll-up; layout optimised for wide format.</li>
          <li>Confirm final dimensions with your printer before production.</li>
        </ul>
        <p>
          <Link href={`/memorial/${slug}/banner/wide`} className="font-medium text-[#C9A02C] underline">
            Open wide banner layout →
          </Link>
        </p>
      </section>

      <section className="mb-6 space-y-2 text-sm">
        <h2 className="font-semibold text-[#3D2B1F]">File checklist</h2>
        <ul className="list-disc space-y-1 pl-5 text-[#1A1A1A]/85">
          <li>PDF from browser print (vector text; raster photos embedded).</li>
          <li>Optional: separate high-res JPEG/PNG of portrait if shop requests.</li>
          <li>Memorial URL for QR verification: {memorialUrl}</li>
        </ul>
      </section>

      <footer className="border-t border-[#3D2B1F]/15 pt-4 text-xs text-[#1A1A1A]/60">
        Generated by Passage ·{' '}
        <Link href={`/memorial/${slug}`} className="underline">
          Public memorial
        </Link>
      </footer>
    </div>
  )
}
